[build]
  publish = "dist/ng-sell"
  command = "npm install --force && ng build --configuration production"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200