[build]
  publish = "dist/ng-sell"
  command = "npm install --force && npm run build --force"

[build.environment]
  NODE_VERSION = "16.13.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200