

import { Tool } from "../interfaces/tool.interface";

export const toolsContent: Tool[] = [
    {
        id: 1,
        title: "TOOLS.TITLE",
        subtitle: "TOOLS.SUBTITLE",
        link: "https://www.adobe.com/products/photoshop.html",
        description: "TOOLS.DESCRIPTION",
        tags: ["TOOLS.TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Adobe_Photoshop_CC_icon.svg/2101px-Adobe_Photoshop_CC_icon.svg.png",
        skill: 60,
        restskill: 40,
        web: "TOOLS.WEB"
    },
    {
        id: 2,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.adobe.com/products/illustrator.html",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Adobe_Illustrator_CC_icon.svg/1051px-Adobe_Illustrator_CC_icon.svg.png",
        skill: 55,
        restskill: 45,
        web: "WEB"
    },
    {
        id: 3,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.adobe.com/products/indesign.html",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Adobe_InDesign_CC_icon.svg/1200px-Adobe_InDesign_CC_icon.svg.png",
        skill: 65,
        restskill: 35,
        web: "WEB"
    },
    {
        id: 4,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.adobe.com/products/xd.html",
        description :"DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://cdn.worldvectorlogo.com/logos/adobe-xd-2.svg",
        skill: 80,
        restskill: 20,
        web: "WEB"
    },
    {
        id: 5,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.figma.com/",
        description :"DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Figma-logo.svg/1365px-Figma-logo.svg.png",
        skill: 75,
        restskill: 25,
        web: "WEB"
    },
    {
        id: 6,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://code.visualstudio.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://seeklogo.com/images/V/visual-studio-code-logo-449D71944F-seeklogo.com.png",
        skill: 90,
        restskill: 10,
        web: "WEB"
    },
    {
        id: 7,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.notion.so/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Notion-logo.svg/2048px-Notion-logo.svg.png",
        skill: 90,
        restskill: 10,
        web: "WEB"
    },
    {
        id: 8,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://trello.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://cdn.worldvectorlogo.com/logos/trello-logo.svg",
        skill: 85,
        restskill: 15,
        web: "WEB"
    },
    {
        id: 9,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.atlassian.com/software/jira",
        description: "DESCRIPTION",
        tags:["TAGS"],
        favorite: true,
        image: "https://cdn.worldvectorlogo.com/logos/jira-3.svg",
        skill: 70,
        restskill: 30,
        web: "WEB"
    },
    {
        id: 10,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/1200px-HTML5_logo_and_wordmark.svg.png",
        skill: 90,
        restskill: 10,
        web: "WEB"
    },
    {
        id: 11,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://cdn.freebiesupply.com/logos/large/2x/css3-logo-png-transparent.png",
        skill: 90,
        restskill: 10,
        web: "WEB"
    },
    {
        id: 12,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://sass-lang.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://cdn.freebiesupply.com/logos/large/2x/sass-1-logo-png-transparent.png",
        skill: 75,
        restskill: 25,
        web: "WEB"
    },
    {
        id: 13,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/1200px-JavaScript-logo.png",
        skill: 55,
        restskill: 45,
        web: "WEB"
    },
    {
        id: 14,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://angular.io/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/1200px-Angular_full_color_logo.svg.png",
        skill: 70,
        restskill: 30,
        web: "WEB"
    },
    {
        id: 15,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://reactjs.org/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png",
        skill: 40,
        restskill: 60,
        web: "WEB"
    },
    {
        id: 16,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://github.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/1200px-Octicons-mark-github.svg.png",
        skill: 80,
        restskill: 20,
        web: "WEB"
    },
    {
        id: 17,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://nodejs.org/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Node.js_logo.svg/1200px-Node.js_logo.svg.png",
        skill: 30,
        restskill: 70,
        web: "WEB"
    },
    {
        id: 18,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.postman.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://seeklogo.com/images/P/postman-logo-F43375A2EB-seeklogo.com.png",
        skill: 30,
        restskill: 70,
        web: "WEB"
    },
    {
        id: 19,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://git-scm.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Git-logo.svg/1200px-Git-logo.svg.png",
        skill: 85,
        restskill: 15,
        web: "WEB"
    },
    {
        id: 20,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://getbootstrap.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1200px-Bootstrap_logo.svg.png",
        skill: 75,
        restskill: 25,
        web: "WEB"
    },
    {
        id: 21,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://material.angular.io/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://cdn.jsdelivr.net/gh/angular-material-extensions/pages@master/assets/angular-material-extensions-logo.png",
        skill: 65,
        restskill: 35,
        web: "WEB"
    },
    {
        id: 22,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.primefaces.org/primeng/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://soka.gitlab.io/angular/ui/primeng/01-primeng-intro/img/primeng-2.png",
        skill: 85,
        restskill: 15,
        web: "WEB"
    },
    {
        id: 23,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.mongodb.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/MongoDB_Logo.svg/1200px-MongoDB_Logo.svg.png",
        skill: 55,
        restskill: 45,
        web: "WEB"
    },
    {
        id: 24,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://wordpress.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/WordPress_blue_logo.svg/1200px-WordPress_blue_logo.svg.png",
        skill: 75,
        restskill: 25,
        web: "WEB"
    },
    {
        id: 25,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://www.docker.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Docker_%28container_engine%29_logo.svg/1200px-Docker_%28container_engine%29_logo.svg.png",
        skill: 25,
        restskill: 75,
        web: "WEB"
    },
    {
        id: 26,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://tailwindcss.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://cdn.worldvectorlogo.com/logos/tailwind-css-1.svg",
        skill: 75,
        restskill: 25,
        web: "WEB"
    },
    {
        id: 27,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://stenciljs.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://stenciljs.com/stencil-og.png",
        skill: 65,
        restskill: 45,
        web: "WEB"
    },
    {
        id: 28,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://storybook.js.org/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: true,
        image: "https://static-00.iconduck.com/assets.00/storybook-icon-2048x410-m440b17u.png",
        skill: 75,
        restskill: 25,
        web: "WEB"
    },
    {
        id: 29,
        title: "TITLE",
        subtitle: "SUBTITLE",
        link: "https://nestjs.com/",
        description: "DESCRIPTION",
        tags: ["TAGS"],
        favorite: false,
        image: "https://cdn.icon-icons.com/icons2/2699/PNG/512/nestjs_logo_icon_169927.png",
        skill: 25,
        restskill: 75,
        web: "WEB"
    }
]